name: Build and Deploy Documentation

on:
  push:
    branches:
      - main  # Adjust to your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"  # Use the Python version you prefer

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Build documentation
    - name: Build HTML
      run: sphinx-build -b html docs build/html

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      run: |
        pip install ghp-import
        ghp-import -n -p -f build/html
